### ISSUE TITLE
Full name

### ISSUE THREAD

**Issue by vr8hub** [standardebooks/andre-norton_star-hunter#4]
While reviewing _Storm Over Warlock_, I noticed that our existing Norton's don't have her full name in the metadata (at least the three I checked). Her name at birth was Alice Mary Norton; her full pseudonym is listed as Andre Alice Norton (see the first paragraph of [Wikipedia](https://en.wikipedia.org/wiki/Andre_Norton)). We have five of her books; do you want PR's, or do you want to just change them yourself? If you want PR's, should we use her actual name or her full pseudonym name? (I looked at one of the Twain's and it had the full name as Samuel <I forget> Clemens, so I'm guessing the former?)

**Comment by acabal** [comment]
We don't include information about the author's real name, in general. So full name metadata isn't necessary because her pen name is her "full name". See George Eliot, Mark Twain, etc.

**Comment by acabal** [comment]
Oops, I see now that her pen name included "Alice" so yes, you can add that as full name metadata in all of those books.

**Comment by vr8hub** [comment]
As I said, I looked at one our Twain's, and it _did_ have his full (real) name. So if we're not supposed to do that, then that's another problem. And we should probably say that in the manual (that we don't add real names); I'll try to come up with something for that, too.
